# Generated by Django 4.0.6 on 2022-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('N', 'Nuevo'), ('P', 'Popular'), ('NR', 'Normal')], max_length=10, null=True)),
                ('animal', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato'), ('H', 'Hamster')], max_length=10, null=True)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pgato',
        ),
        migrations.DeleteModel(
            name='Phamster',
        ),
        migrations.DeleteModel(
            name='Pnuevo',
        ),
        migrations.DeleteModel(
            name='Pperro',
        ),
        migrations.DeleteModel(
            name='Ppopulare',
        ),
    ]
